### ISSUE TITLE
OLD PHONE - OutOfMemoryError

### ISSUE THREAD

**Issue by godonefiftyone** [godonefiftyone/MeetingTracker#30]
java.lang.RuntimeException: java.lang.OutOfMemoryError
at com.godonefiftyone.meetingtracker.XMPPUtils.loadImage(XMPPUtils.java:309)
at com.godonefiftyone.meetingtracker.XMPPUtils.getImageById(XMPPUtils.java:270)
at com.godonefiftyone.meetingtracker.BitmapBuffer.getImageByImageId(BitmapBuffer.java:30)
at com.godonefiftyone.meetingtracker.BitmapBuffer.getImageByUserId(BitmapBuffer.java:22)
at com.godonefiftyone.meetingtracker.CnvrstnFragment$CnvrstnHolder.bindCnvrstn(CnvrstnFragment.java:263)
at com.godonefiftyone.meetingtracker.CnvrstnFragment$CnvrstnAdapter.onBindViewHolder(CnvrstnFragment.java:318)
at com.godonefiftyone.meetingtracker.CnvrstnFragment$CnvrstnAdapter.onBindViewHolder(CnvrstnFragment.java:308)

**Comment by godonefiftyone** [comment]
Try a release build instead of a debug build.

**Comment by godonefiftyone** [comment]
Using release apk seems to work for a minute...
