### ISSUE TITLE
Notifications still getting lost

### ISSUE THREAD

**Issue by godonefiftyone** [godonefiftyone/MeetingTracker#34]
wtf?

Test after power cycle, in doze, etc.

NOTE: Implement retry (in case network down)

**Comment by godonefiftyone** [comment]
Login failing in GcmMsgListenerService:

1-11 09:13:16.885 26376-26393/com.godonefiftyone.meetingtracker.debug D/XMPPUtils: check login() start.
11-11 09:13:17.922 26376-26393/com.godonefiftyone.meetingtracker.debug E/XMPPUtils: Client side error during login.
org.jivesoftware.smack.SmackException$ConnectionException: The following addresses failed: 'godonefiftyone.xyz:5222' failed because java.net.SocketException: Socket closed
	at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectUsingConfiguration(XMPPTCPConnection.java:609)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectInternal(XMPPTCPConnection.java:847)
	at org.jivesoftware.smack.AbstractXMPPConnection.connect(AbstractXMPPConnection.java:364)
	at com.godonefiftyone.meetingtracker.XMPPUtils.loginToXmppServer(XMPPUtils.java:58)
	at com.godonefiftyone.meetingtracker.XMPPUtils.login(XMPPUtils.java:183)
	at com.godonefiftyone.meetingtracker.XMPPUtils.executeCommand(XMPPUtils.java:69)
	at com.godonefiftyone.meetingtracker.NotifyThing.getMissedMessagesAndNotify(NotifyThing.java:62)
	at com.godonefiftyone.meetingtracker.GcmMsgListenerService.onMessageReceived(GcmMsgListenerService.java:24)
	at com.google.android.gms.gcm.GcmListenerService.zzo(Unknown Source:55)
	at com.google.android.gms.gcm.GcmListenerService.zzn(Unknown Source:91)
	at com.google.android.gms.gcm.GcmListenerService.zzm(Unknown Source:60)
	at com.google.android.gms.gcm.GcmListenerService.zza(Unknown Source:0)
	at com.google.android.gms.gcm.GcmListenerService$1.run(Unknown Source:4)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
11-11 09:13:17.930 26376-26393/com.godonefiftyone.meetingtracker.debug W/WakefulBroadcastReceiver: No active wake lock id #1
11-11 09:13:17.936 26376-26393/com.godonefiftyone.meetingtracker.debug E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
	 Process: com.godonefiftyone.meetingtracker.debug, PID: 26376
	 java.lang.NullPointerException: Attempt to invoke virtual method 'com.godonefiftyone.xmpp.command.Response com.godonefiftyone.xmpp.command.CommandContext.sendAndWait(com.godonefiftyone.xmpp.command.Request, java.lang.String, int)' on a null object reference
		 at com.godonefiftyone.meetingtracker.XMPPUtils.executeCommand(XMPPUtils.java:73)
		 at com.godonefiftyone.meetingtracker.NotifyThing.getMissedMessagesAndNotify(NotifyThing.java:62)
		 at com.godonefiftyone.meetingtracker.GcmMsgListenerService.onMessageReceived(GcmMsgListenerService.java:24)
		 at com.google.android.gms.gcm.GcmListenerService.zzo(Unknown Source:55)
		 at com.google.android.gms.gcm.GcmListenerService.zzn(Unknown Source:91)
		 at com.google.android.gms.gcm.GcmListenerService.zzm(Unknown Source:60)
		 at com.google.android.gms.gcm.GcmListenerService.zza(Unknown Source:0)
		 at com.google.android.gms.gcm.GcmListenerService$1.run(Unknown Source:4)
		 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
		 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
		 at java.lang.Thread.run(Thread.java:764)
11-11 09:13:17.948 26376-26393/com.godonefiftyone.meetingtracker.debug I/Process: Sending signal. PID: 26376 SIG: 9
